service: resize-lambda-serverless
frameworkVersion: '2'
provider:
  name: aws
  runtime: ruby2.7
  region: ap-northeast-1
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::yuichi-kojima-test2/*"
functions:
  image_resizer:
    handler: handler.handler
    layers:
      - arn:aws:lambda:ap-northeast-1:046977594715:layer:sample-rubyvips8100-27:1
    events:
      - s3:
          bucket: yuichi-kojima-test2
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: uploads
          existing: true
package:
  exclude:
    - .git
    - .gitignore
    - docker.env
    - docker.env.sample
    - docker-compose.yml
    - Dockerfile.dev
